stages:
 - template: azure/stages.yml@templates
   parameters:
     benches: true
     minrust: false
     codecov_token: $(CODECOV_TOKEN_SECRET)
     test_ignored: true
     nightly_coverage: true

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: djc
