[package]
name = "bench"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
publish = false

[dependencies]
quinn = { path = "../quinn" }
tokio = "0.2.1"
tracing = "0.1.9"
tracing-subscriber = "0.1.5"
anyhow = "1.0.22"
rcgen = "0.7"
futures = "0.3.1"
rustls = "0.16"

[[bin]]
name = "bulk"
path = "src/bulk.rs"
