[package]
name = "quinn"
version = "0.4.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>", "Dirkjan Ochtman <dirkjan@ochtman.nl>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/djc/quinn"
description = "QUIC transport protocol implementation for Tokio"
readme = "../README.md"
keywords = ["quic"]
categories = [ "network-programming", "asynchronous" ]
workspace = ".."
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["native-certs", "ct-logs"]
# Trust the contents of the OS certificate store by default
native-certs = [ "rustls-native-certs" ]

[badges]
codecov = { repository = "djc/quinn" }
maintenance = { status = "experimental" }
azure-devops = { project = "dochtman/Projects", pipeline = "Quinn", build = "1" }

[dependencies]
bytes = "0.5.1"
ct-logs = { version = "0.6", optional = true }
err-derive = "0.2"
futures = "0.3.1"
libc = "0.2.49"
mio = "0.6"
proto = { package = "quinn-proto", path = "../quinn-proto", version = "0.4.0" }
rustls = { version = "0.16", features = ["quic"] }
tracing = "0.1.9"
tokio = { version = "0.2.1", features = ["io-driver", "time"] }
webpki = "0.21"
rustls-native-certs = { version = "0.1.0", optional = true }

[dev-dependencies]
crc = "1.8.1"
criterion = "0.3"
directories = "2.0.0"
rand = "0.7"
rcgen = "0.7"
tokio = { version = "0.2.1", features = ["rt-core", "rt-util"] }
tracing-subscriber = "0.1.5"
tracing-futures = { version = "0.1.0", default-features = false, features = ["std-future"] }
structopt = "0.3.0"
unwrap = "1.2.1"
url = "2"
anyhow = "1.0.23"

[[example]]
name = "server"

[[example]]
name = "client"

[[example]]
name = "insecure_connection"
required-features = ["rustls/dangerous_configuration"]

[[bench]]
name = "bench"
harness = false
